[BUILD] fix compilation error on Android
Disable Vulkan beta extensions to prevent build errors caused by missing
vulkan_beta.h' in the Android NDK/toolchain and to ensure binary stability.

Error:
[...]/llvm/prebuilt/linux-x86_64/bin/../sysroot
/usr/include/vulkan/vulkan.h:88:10: fatal error:
'vulkan_beta.h' file not found

#include "vulkan_beta.h"